### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by dheerajbred** [OpenFlutter/neeko#18]
Hi,

The example is giving me a blank white screen

```
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                         8.4s
W/Gralloc3(22024): mapper 3.x is not supported                          
I/OpenGLRenderer(22024): Davey! duration=1041ms; Flags=1, IntendedVsync=79475952895189, Vsync=79475952895189, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=79475961771659, AnimationStart=79475961837857, PerformTraversalsStart=79475961840930, DrawStart=79476953837388, SyncQueued=79476954646763, SyncStart=79476954962284, IssueDrawCommandsStart=79476955144367, SwapBuffers=79476993865617, FrameCompleted=79476994898325, DequeueBufferDuration=5330000, QueueBufferDuration=684000,
W/Looper  (22024): Slow Looper main: Long Msg: seq=9 plan=20:20:06.448  late=9ms wall=1034ms running=0ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver
W/example.exampl(22024): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl(22024): Init badc2f7 [ExoPlayerLib/2.9.6] [curtana, Redmi Note 9 Pro, Xiaomi, 29]
I/Choreographer(22024): Skipped 64 frames!  The application may be doing too much work on its main thread.
W/Looper  (22024): Slow Looper main: doFrame is 1078ms late because of 2 msg, msg 1 took 1034ms (seq=9 late=9ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
I/DpmTcmClient(22024): RegisterTcmMonitor from: $Proxy0
E/AccessibilityBridge(22024): VirtualView node must not be the root node.
D/NetworkSecurityConfig(22024): No Network Security Config specified, using platform default
Syncing files to device Redmi Note 9 Pro...                             
E/ExoPlayerImplInternal(22024): Source error.
E/ExoPlayerImplInternal(22024): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://vfx.mtime.cn/Video/2019/03/09/mp4/190309153658147087.mp4
E/ExoPlayerImplInternal(22024):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
E/ExoPlayerImplInternal(22024):         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(22024):         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(22024):         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(22024):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(22024):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(22024):         at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(22024): Caused by: java.io.IOException: Cleartext HTTP traffic to vfx.mtime.cn not permitted
E/ExoPlayerImplInternal(22024):         at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
E/ExoPlayerImplInternal(22024):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)        
E/ExoPlayerImplInternal(22024):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal(22024):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)
E/ExoPlayerImplInternal(22024):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:444)
E/ExoPlayerImplInternal(22024):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
E/ExoPlayerImplInternal(22024):         ... 6 more
E/flutter (22024): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://vfx.mtime.cn/Video/2019/03/09/mp4/190309153658147087.mp4, null)
E/flutter (22024): #0      VideoControllerWrapper.prepareDataSource (package:neeko/src/video_controller_wrapper.dart:63:5)
E/flutter (22024): <asynchronous suspension>
E/flutter (22024): #1      new VideoControllerWrapper (package:neeko/src/video_controller_wrapper.dart:32:5)
E/flutter (22024): #2      new _MyHomePageState (package:example/main.dart:44:57)
E/flutter (22024): #3      MyHomePage.createState (package:example/main.dart:36:37)
E/flutter (22024): #4      new StatefulElement (package:flutter/src/widgets/framework.dart:4306:25)
E/flutter (22024): #5      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:809:38)
E/flutter (22024): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3189:40)
E/flutter (22024): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (22024): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (22024): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (22024): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (22024): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (22024): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (22024): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (22024): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (22024): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (22024): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (22024): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (22024): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (22024): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (22024): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (22024): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (22024): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (22024): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (22024): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (22024): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (22024): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (22024): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (22024): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (22024): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (22024): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (22024): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (22024): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (22024): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (22024): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (22024): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (22024): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)    
E/flutter (22024): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (22024): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (22024): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)        
E/flutter (22024): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (22024): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (22024): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (22024): #43     ComponentElement.perfor
I/example.exampl(22024): ProcessProfilingInfo new_methods=1068 is saved saved_to_disk=1 resolve_classes_delay=8000
Syncing files to device Redmi Note 9 Pro...                      7,593ms (!)

�🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Redmi Note 9 Pro is available at: http://127.0.0.1:58828/Cxy2vxtGtf8=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

```

**Comment by JarvanMo** [comment]
Video in example is not https.
